; AH = 0x14
; SI = Path to file.
; DH = File attributes.
MAKE_FILE_INT:
        CALL MAKE_ENTRY_PROC
	MOV BYTE[INT_RET_CODE], DH
        JC RET_CODE_INT

        MOV SI, FILENAME_BUFFER
        CALL CREATE_ENTRY
        JNC .NO_ERROR

        MOV BYTE[INT_RET_CODE], AL
        JMP RET_CODE_INT

.NO_ERROR:
        CALL GET_DIRECTORY_SIZE
        CALL STORE_DIRECTORY
        JC ENTRY_WRITE_ERROR

        JMP RET_CODE_INT
