; AH = 0x14
; SI = Path to file.
MAKE_FILE_INT:
        CALL MAKE_ENTRY_PROC
        JC RET_CODE_INT

        MOV SI, FILENAME_BUFFER
        CALL CREATE_ENTRY
        JNC .NO_ERROR

        MOV BYTE[INT_RET_CODE], AL
        JMP RET_CODE_INT

.NO_ERROR:
        MOV WORD[ES:DI + 26], 0
        MOV WORD[ES:DI + 28], 0
        MOV WORD[ES:DI + 30], 0
        MOV BYTE[ES:DI + 11], 0

        CALL GET_DIRECTORY_SIZE
        CALL STORE_DIRECTORY
        JC ENTRY_WRITE_ERROR

        JMP RET_CODE_INT
